#!/bin/sh
#
#
#############
###<Notes>###
#############
# This script depends on dtach.
# Based on the script created by lostnihilist at http://libtorrent.rakshasa.no/attachment/wiki/RTorrentCommonTasks/rtorrentInit.sh
# Licensed under the GPLv2 by average_geek: contact_at_theaveragegeek_dot_com
##############
###</Notes>###
##############
#/etc/rc.d/init.d/rtorrent
# chkconfig: 235 80 30
# description: Run rtorrent as a Daemon service using dtach
# processname: rtorrent
# Source function library.
. /etc/rc.d/init.d/functions
# Source networking configuration.
. /etc/sysconfig/network
#VARIABLES#
. /etc/rtorrent.init.conf
PATH=/usr/bin:/usr/local/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin
DESC="rtorrent via dtach"
NAME=rtorrent
DAEMON=$NAME
SCRIPTNAME=/etc/init.d/$NAME
RETVAL=0
lockfile=${LOCKFILE-/var/lock/subsys/rtorrent}

# Check that networking is up.
[ ${NETWORKING} = "no" ] && exit 0

#Functions
checkconfig() {
	exists=0

	for i in `echo "$PATH" | tr ':' '\n'` ; do
		if [ -f $i/$NAME ] ; then
			exists=1
			appdir=$i
			apppath=$i/$NAME
			break
		fi
	done

	if ! [ -x "$apppath" ] ; then
		echo "cannot find executable rtorrent binary in PATH $appdir" | tee -a "$logfile" >&2
		exit 3
	fi
	
	if [ $exists -eq 0 ] ; then
			echo "cannot find rtorrent binary in PATH $PATH" | tee -a "$logfile" >&2
			exit 3
	fi

	if ! [ -r "${config}" ] ; then 
		echo "cannot find readable config ${config}. check that it is there and permissions are appropriate" | tee -a "$logfile" >&2
		exit 3 
	fi 

	session=`getsession "$config"` 
	if ! [ -d "${session}" ] ; then
		echo "cannot find readable session directory ${session} from config ${config}. check permissions" | tee -a "$logfile" >&2
		exit 3
	fi
}

getsession() { 

	session=`awk '/^[[:space:]]*session[[:space:]]*=[[:space:]]*/{print($3)}' "$config"`
	echo $session
}

start() {

  daemon `su -c "dtach -n /tmp/dtach-"${DAEMON}" rtorrent ${options} 2>&1 1>/dev/null" ${user} | tee -a "$logfile" >&2`

  RETVAL=$?
  echo
  [ $RETVAL -eq 0 ] && touch ${lockfile}

}

stop() {
	
	killproc $NAME
	
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && rm -f ${lockfile}

}
#End Functions
#Script

checkconfig

case "$1" in

  start)
	echo -n "Starting $DESC: $NAME"
	start
	;;

  stop)
	echo -n "Stopping $DESC: $NAME"
	stop
	;;

  restart|force-reload)
	echo -n "Restarting $DESC: $NAME"
	stop
	sleep 1
	start
	;;

  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
	exit 1
	;;

esac

exit 0


